---
name: Daily data updater
on:
  schedule:
    - cron: '1 21 * * *'
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: ctrlaltf2/pyrun@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
