---
name: Daily data updater
on:
  schedule:
    - cron: '31 22 * * *'
jobs:
  fetch:
    name: Fetch data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
    - name: Setup python
      uses: actions/setup-python@v1
    - name: Fetch data from Health Department website
      run: python3 ./fetch_data.py
